services:
  #postgreSQL
  postgres:
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA : /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    networks:
      - microservice-network
    restart: unless-stopped

  #keyclock
  keycloak:
    container_name: keycloak-auth
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      KEYCLOAK_CREATE_ADMIN: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5433
      KEYCLOAK_DATABASE_USER: pharmacie
      KEYCLOAK_DATABASE_NAME: root
      KEYCLOAK_DATABASE_PASSWORD: root
    ports:
      - "8080:8080"
    command:
      - "start-dev"

networks:
  microservice-network:
    driver: bridge

volumes:
  postgres:

