server:
  port: 8181

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pharmacy-db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Pharmacie-Realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
jwt:
  auth:
    converter:
      resource-id: pharmacie-Client
      principle-attribute: preferred_username
